module.exports = {
  DatesRangesValidator: require('./DatesRangesValidator'),
  DatesValidator: require('./DatesValidator'),
  FirstLetterValidator: require('./FirstLetterValidator'),
  NumbersRangesValidator: require('./NumbersRangesValidator'),
  NumbersValuesValidator: require('./NumbersValuesValidator'),
  StringsLengthsValidator: require('./StringsLengthsValidator'),
  PointsValueValidator: require('./PointsValueValidator'),
  ContestValidator: require('./ContestValidator'),
  ContestRewardValidator: require('./ContestRewardValidator'),
  ContestVoteCategoryValidator: require('./ContestVoteCategoryValidator'),
  ContestRuleValidator: require('./ContestRuleValidator'),
  ContestEntryValidator: require('./ContestEntryValidator'),
  ReasonValidator: require('./ReasonValidator'),
  PointsValidator: require('./PointsValidator'),
  CommandValidator: require('./CommandValidator'),
  MemberValidator: require('./MemberValidator'),
  RoleValidator: require('./RoleValidator'),
}
